[package]
name = "minecraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy-tokio-tasks = "0.10.1"
dashmap = "5.4.0"
tokio = "1.27.0"
valence = { git = "https://github.com/valence-rs/valence.git" }
